--- GNUmakefile.orig	2012-05-22 02:48:16.968890726 +0700
+++ GNUmakefile	2012-05-22 02:52:21.348879831 +0700
@@ -140,7 +140,7 @@
 
 install: install_ctb_lib install_ctb_dll
 	$(INSTALL) -d $(DESTDIR)$(prefix)/include/ctb-0.16
-	for f in ctb.h fifo.h getopt.h $(GPIBINC) iobase.h linux/serport.h linux/timer.h portscan.h serport.h serportx.h timer.h; do \
+	for f in ctb.h fifo.h getopt.h $(GPIBINC) iobase.h kbhit.h linux/serport.h linux/timer.h portscan.h serport.h serportx.h timer.h; do \
 	if test ! -d $(DESTDIR)$(prefix)/include/ctb-0.16/`dirname $$f` ; then \
 	$(INSTALL) -d $(DESTDIR)$(prefix)/include/ctb-0.16/`dirname $$f`; \
 	fi; \
@@ -148,7 +148,7 @@
 	done
 
 uninstall: uninstall_ctb_lib uninstall_ctb_dll
-	for f in ctb.h fifo.h getopt.h $(GPIBINC) iobase.h linux/serport.h linux/timer.h portscan.h serport.h serportx.h timer.h; do \
+	for f in ctb.h fifo.h getopt.h $(GPIBINC) iobase.h kbhit.h linux/serport.h linux/timer.h portscan.h serport.h serportx.h timer.h; do \
 	rm -f $(DESTDIR)$(prefix)/include/ctb-0.16/$$f; \
 	done
 
